define([], function() {
  return {
  "ConfigureWebPart": "Please enable dynamic properties configuration in the property pane.",
  "EmptyConfigure": "Configure webpart and add tabs to display tagged items",
  "EmptyData": "No results with selected term",
  "EmptyDescription": "No description available for the selected term",
  "Yes": "Yes",
  "No": "No",
  "loading": "Loading...",
  "WebPartTitle": "Webpart title",
  "PropertyPaneGroupTerms": "Term settings",
  "PropertyPaneGroupConnectors": "Connect to other webpart",
  "PropertyPaneGroupTabs": "Tabs settings",
  "PropertyPaneGroupColumns": "Columns configuration settings",
  "PropertyPaneLabelConnectors": "Use dynamic term filter",
  "PropertyPaneGroupList": "List settings",
  "FieldLabelProcessObjectList": "Select a list for process description",
  "FieldLabelTermPicker": "Select default term",
  "FieldLabelTermColumn": "Select term column",
  "PanelTitleTermPicker": "Select a term",
  "ButtonLabelManageTabs": "Manage tabs",
  "PanelTitleManageTabs": "Manage tabs",
  "TabTitleOrder": "Order of tab",
  "TabTitleName": "Tab name",
  "TabTitleIcon": "Icon",
  "TabTitleShowIcon": "Show icon",
  "TabTitleSource": "Source",
  "TabTitleType": "Type",
  "TabSourceEmpty": "Select a type first...",
  "TypeTextDescription": "Description",
  "TypeTextDocument": "Document",
  "TypeTextList": "List",
  "TypeTextPages": "Pages",
  "TypeTextLinks": "Links",
  "connectedEmpty": "Select an item in the image above to display the content here",
  "notConnectedEmpty": "No term selected",
  "noData": "Either no items match your search criteria or you do not have permission to view them.",
  "sortasc": "A to Z",
  "sortdesc": "Z to A",
  "oldToNew": "Older to newer",
  "newToOld": "Newer to older",
  "filter": "Filter by",
  "ColumnNameTitle": "Title",
  "ColumnNameDescription": "Description"
  }
})