define([], function() {
  return {
    "ConfigureWebPart": "Vänligen aktivera konfiguration av dynamiska egenskaper i egenskapsfönstret.",
    "EmptyConfigure": "Konfigurera webdel och lägg till flikar för att visa taggade objekt",
    "EmptyData": "Inga resultat med vald term",
    "EmptyDescription": "Ingen beskrivning tillgänglig för den valda termen",
    "Yes": "Ja",
    "No": "Nej",
    "loading": "Laddar...",
    "WebPartTitle": "Webdels titel",
    "PropertyPaneGroupTerms": "Term inställningar",
    "PropertyPaneGroupConnectors": "Anslut till andra webdelar",
    "PropertyPaneGroupTabs": "Flikinställningar",
    "PropertyPaneGroupColumns": "Kolumnkonfigurationsinställningar",
    "PropertyPaneLabelConnectors": "Använd dynamisk termfilter",
    "PropertyPaneGroupList": "Listinställningar",
    "FieldLabelProcessObjectList": "Välj en lista för process beskrivning",
    "FieldLabelTermPicker": "Välj en standardterm",
    "FieldLabelTermColumn": "Välj termkolumn",
    "PanelTitleTermPicker": "Välj en term",
    "ButtonLabelManageTabs": "Hantera flikar",
    "PanelTitleManageTabs": "Hantera flikar",
    "TabTitleOrder": "Flikens ordning",
    "TabTitleName": "Flikens namn",
    "TabTitleIcon": "Ikon",
    "TabTitleShowIcon": "Visa ikon",
    "TabTitleSource": "Källa",
    "TabTitleType": "Typ",
    "TabSourceEmpty": "Välj först en typ...",
    "TypeTextDescription": "Beskrivning",
    "TypeTextDocument": "Dokument",
    "TypeTextList": "Lista",
    "TypeTextPages": "Sidor",
    "TypeTextLinks": "Länkar",
    "connectedEmpty": "Välj ett objekt i bilden ovan för att visa innehållet här",
    "notConnectedEmpty": "Ingen term är vald",
    "noData": "Antingen matchar inga objekt dina sökkriterier eller så har du inte behörighet att se dem.",
    "sortasc": "A till Ö",
    "sortdesc": "Ö till A",
    "oldToNew": "Äldre först",
    "newToOld": "Nyare först",
    "filter": "Filtrera efter",
    "ColumnNameTitle": "Titel",
    "ColumnNameDescription": "Beskrivning"
  }
})